web:
   image: tutum/apache-php
   container_name: apache-php
   ports:
     - "2000:80"
   links:
     - db
   volumes:
     - ./app:/app

db:
  image: mariadb
  container_name: mariadb
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: root
    MYSQL_PASSWORD: root
    MYSQL_DATABASE: database
    DB_ADMIN_PASS: pass
  ports:
    - "3000:3306"

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: admin
  links: 
    - db
  ports: 
    - "4000:80"