web:
   image: tutum/apache-php
   ports:
     - "8000:80"
   links:
     - db
   volumes:
     - ./app:/app

db:
  image: mariadb
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: root
    MYSQL_PASSWORD: root
    MYSQL_DATABASE: database
  ports:
    - "3000:3306"